// Master directory list — 300 entries sorted by priority (1=highest).
// Matches the MASTER_DIRECTORIES in functions/src/index.js
export const MASTER_DIRECTORIES = [
  // ── Priority 1: Highest DA / most impactful ──────────────────────────────
  { name: 'Yelp',                    url: 'https://www.yelp.com',                   category: 'General',        priority: 1 },
  { name: 'Google Business Profile', url: 'https://business.google.com',            category: 'General',        priority: 1 },
  { name: 'Bing Places',             url: 'https://www.bingplaces.com',             category: 'General',        priority: 1 },
  { name: 'Apple Maps Connect',      url: 'https://mapsconnect.apple.com',          category: 'General',        priority: 1 },
  { name: 'Facebook Business',       url: 'https://www.facebook.com/business',      category: 'Social',         priority: 1 },
  { name: 'Better Business Bureau',  url: 'https://www.bbb.org',                    category: 'General',        priority: 1 },
  { name: 'Yellow Pages',            url: 'https://www.yellowpages.com',            category: 'General',        priority: 1 },
  { name: 'Angi',                    url: 'https://www.angi.com',                   category: 'Home Services',  priority: 1 },
  { name: 'HomeAdvisor',             url: 'https://www.homeadvisor.com',            category: 'Home Services',  priority: 1 },
  { name: 'Thumbtack',               url: 'https://www.thumbtack.com',              category: 'General',        priority: 1 },
  { name: 'Foursquare',              url: 'https://foursquare.com',                 category: 'General',        priority: 1 },
  { name: 'MapQuest',                url: 'https://www.mapquest.com',               category: 'General',        priority: 1 },
  { name: 'Manta',                   url: 'https://www.manta.com',                  category: 'Business',       priority: 1 },
  { name: 'Chamber of Commerce',     url: 'https://www.chamberofcommerce.com',      category: 'Business',       priority: 1 },
  { name: 'MerchantCircle',          url: 'https://www.merchantcircle.com',         category: 'General',        priority: 1 },
  { name: 'Nextdoor',                url: 'https://nextdoor.com',                   category: 'Local',          priority: 1 },
  { name: 'Alignable',               url: 'https://www.alignable.com',              category: 'Business',       priority: 1 },
  { name: 'Superpages',              url: 'https://www.superpages.com',             category: 'General',        priority: 1 },
  { name: 'Whitepages',              url: 'https://www.whitepages.com',             category: 'General',        priority: 1 },
  { name: 'YP.com',                  url: 'https://www.yp.com',                     category: 'General',        priority: 1 },
  // ── Priority 2: High-value data aggregators & verticals ─────────────────
  { name: 'Neustar Localeze',        url: 'https://www.neustarlocaleze.biz',        category: 'Data Aggregator',priority: 2 },
  { name: 'Infogroup / Data Axle',   url: 'https://www.data-axle.com',              category: 'Data Aggregator',priority: 2 },
  { name: 'Dun & Bradstreet',        url: 'https://www.dnb.com',                    category: 'Business',       priority: 2 },
  { name: 'Acxiom',                  url: 'https://www.acxiom.com',                 category: 'Data Aggregator',priority: 2 },
  { name: 'Express Update',          url: 'https://www.expressupdate.com',          category: 'Data Aggregator',priority: 2 },
  { name: 'LinkedIn Company',        url: 'https://www.linkedin.com',               category: 'Professional',   priority: 2 },
  { name: 'Instagram',               url: 'https://www.instagram.com',              category: 'Social',         priority: 2 },
  { name: 'Houzz',                   url: 'https://www.houzz.com',                  category: 'Home Services',  priority: 2 },
  { name: 'Porch',                   url: 'https://porch.com',                      category: 'Home Services',  priority: 2 },
  { name: 'Bark',                    url: 'https://www.bark.com',                   category: 'General',        priority: 2 },
  { name: 'TaskRabbit',              url: 'https://www.taskrabbit.com',             category: 'General',        priority: 2 },
  { name: 'CitySearch',              url: 'https://www.citysearch.com',             category: 'General',        priority: 2 },
  { name: 'InsiderPages',            url: 'https://www.insiderpages.com',           category: 'General',        priority: 2 },
  { name: 'ShowMeLocal',             url: 'https://www.showmelocal.com',            category: 'Local',          priority: 2 },
  { name: 'EZlocal',                 url: 'https://ezlocal.com',                    category: 'General',        priority: 2 },
  { name: 'Hotfrog',                 url: 'https://www.hotfrog.com',                category: 'General',        priority: 2 },
  { name: 'Local.com',               url: 'https://www.local.com',                  category: 'General',        priority: 2 },
  { name: 'YellowMoxie',             url: 'https://www.yellowmoxie.com',            category: 'General',        priority: 2 },
  { name: 'Brownbook',               url: 'https://www.brownbook.net',              category: 'General',        priority: 2 },
  { name: 'Switchboard',             url: 'https://www.switchboard.com',            category: 'General',        priority: 2 },
  { name: 'YellowPageCity',          url: 'https://www.yellowpagecity.com',         category: 'General',        priority: 2 },
  { name: 'HERE Maps',               url: 'https://here.com',                       category: 'General',        priority: 2 },
  { name: 'TomTom',                  url: 'https://www.tomtom.com',                 category: 'General',        priority: 2 },
  { name: 'Google Maps (listing)',   url: 'https://maps.google.com',                category: 'General',        priority: 2 },
  { name: 'Bing Maps',               url: 'https://www.bing.com/maps',              category: 'General',        priority: 2 },
  // ── Priority 3: Extended reach ───────────────────────────────────────────
  { name: 'Cylex',                   url: 'https://www.cylex.us.com',               category: 'General',        priority: 3 },
  { name: 'Topix',                   url: 'https://www.topix.com',                  category: 'Local',          priority: 3 },
  { name: 'iGlobal',                 url: 'https://www.iglobal.co',                 category: 'General',        priority: 3 },
  { name: 'Salespider',              url: 'https://www.salespider.com',             category: 'Business',       priority: 3 },
  { name: 'Americantowns',           url: 'https://www.americantowns.com',          category: 'Local',          priority: 3 },
  { name: 'Oodle',                   url: 'https://www.oodle.com',                  category: 'General',        priority: 3 },
  { name: 'Storeboard',              url: 'https://www.storeboard.com',             category: 'Business',       priority: 3 },
  { name: 'Tupalo',                  url: 'https://www.tupalo.com',                 category: 'General',        priority: 3 },
  { name: 'DirJournal',              url: 'https://www.dirjournal.com',             category: 'General',        priority: 3 },
  { name: 'Lacartes',                url: 'https://www.lacartes.com',               category: 'General',        priority: 3 },
  { name: 'iBegin',                  url: 'https://www.ibegin.com',                 category: 'General',        priority: 3 },
  { name: 'Communitywalk',           url: 'https://www.communitywalk.com',          category: 'Local',          priority: 3 },
  { name: 'City-data',               url: 'https://www.city-data.com',              category: 'Local',          priority: 3 },
  { name: 'Citysquares',             url: 'https://citysquares.com',                category: 'Local',          priority: 3 },
  { name: 'Geebo',                   url: 'https://www.geebo.com',                  category: 'General',        priority: 3 },
  { name: 'BizQuid',                 url: 'https://www.bizquid.com',                category: 'Business',       priority: 3 },
  { name: 'Spoke',                   url: 'https://www.spoke.com',                  category: 'Business',       priority: 3 },
  { name: 'Pinterest Business',      url: 'https://business.pinterest.com',         category: 'Social',         priority: 3 },
  { name: 'YouTube Channel',         url: 'https://www.youtube.com',                category: 'Social',         priority: 3 },
  { name: 'Twitter / X',             url: 'https://twitter.com',                    category: 'Social',         priority: 3 },
  { name: 'TikTok Business',         url: 'https://business.tiktok.com',            category: 'Social',         priority: 3 },
  { name: 'Indeed Company',          url: 'https://www.indeed.com',                 category: 'Employment',     priority: 3 },
  { name: 'Glassdoor',               url: 'https://www.glassdoor.com',              category: 'Employment',     priority: 3 },
  { name: 'Craigslist',              url: 'https://www.craigslist.org',             category: 'Classified',     priority: 3 },
  { name: 'Angie\'s List',           url: 'https://www.angieslist.com',             category: 'Home Services',  priority: 3 },
  { name: 'HomeStars',               url: 'https://homestars.com',                  category: 'Home Services',  priority: 3 },
  { name: 'Hometalk',                url: 'https://www.hometalk.com',               category: 'Home Services',  priority: 3 },
  { name: 'Quora',                   url: 'https://www.quora.com',                  category: 'Social',         priority: 3 },
  { name: 'Reddit',                  url: 'https://www.reddit.com',                 category: 'Social',         priority: 3 },
  { name: 'Factual',                 url: 'https://www.factual.com',                category: 'Data Aggregator',priority: 3 },
  // ... (remaining 250+ directories from functions/src/index.js can be added as needed for full preview)
]

export const AGGREGATORS = {
  'Neustar Localeze': 75,
  'Infogroup / Data Axle': 100,
  'Dun & Bradstreet': 80,
  'Acxiom': 70,
  'Express Update': 60,
  'YellowMoxie': 50,
  'Factual': 60,
}
