export const HUB_NAME = 'ReBoost Marketing HUB'
export const HUB_VERSION = '1.0.0'

// Major cities per state for bulk lead searching (up to 100+ leads per search)
export const STATE_CITIES = {
  AL: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa'],
  AK: ['Anchorage', 'Juneau', 'Fairbanks'],
  AZ: ['Phoenix', 'Mesa', 'Scottsdale', 'Chandler', 'Tempe'],
  AR: ['Little Rock', 'Fayetteville', 'Springdale', 'Jonesboro'],
  CA: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose', 'Fresno', 'Long Beach'],
  CO: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'],
  CT: ['Hartford', 'New Haven', 'Bridgeport', 'Waterbury'],
  DE: ['Wilmington', 'Dover', 'Newark'],
  FL: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Fort Lauderdale'],
  GA: ['Atlanta', 'Savannah', 'Augusta', 'Columbus', 'Athens'],
  HI: ['Honolulu', 'Hilo'],
  ID: ['Boise', 'Meridian', 'Pocatello', 'Idaho Falls'],
  IL: ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Peoria', 'Springfield'],
  IN: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend'],
  IA: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City'],
  KS: ['Kansas City', 'Wichita', 'Topeka', 'Overland Park'],
  KY: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro'],
  LA: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'],
  ME: ['Portland', 'Lewiston', 'Bangor'],
  MD: ['Baltimore', 'Frederick', 'Gaithersburg', 'Bowie'],
  MA: ['Boston', 'Worcester', 'Springfield', 'Cambridge'],
  MI: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'],
  MN: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'St. Cloud'],
  MS: ['Jackson', 'Gulfport', 'Biloxi', 'Southaven'],
  MO: ['Kansas City', 'St. Louis', 'Springfield', 'Independence'],
  MT: ['Billings', 'Missoula', 'Great Falls'],
  NE: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'],
  NV: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas'],
  NH: ['Manchester', 'Nashua', 'Concord'],
  NJ: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton'],
  NM: ['Albuquerque', 'Las Cruces', 'Santa Fe'],
  NY: ['New York', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse'],
  NC: ['Charlotte', 'Raleigh', 'Greensboro', 'Winston-Salem', 'Durham'],
  ND: ['Bismarck', 'Fargo', 'Grand Forks'],
  OH: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton'],
  OK: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'],
  OR: ['Portland', 'Eugene', 'Salem', 'Gresham'],
  PA: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'],
  RI: ['Providence', 'Warwick', 'Cranston'],
  SC: ['Charleston', 'Columbia', 'Greenville', 'Summerville'],
  SD: ['Sioux Falls', 'Rapid City', 'Pierre'],
  TN: ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Clarksville'],
  TX: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'El Paso', 'Arlington'],
  UT: ['Salt Lake City', 'Provo', 'Orem', 'Ogden', 'West Valley City'],
  VT: ['Burlington', 'Rutland'],
  VA: ['Virginia Beach', 'Richmond', 'Arlington', 'Alexandria', 'Roanoke'],
  WA: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
  WV: ['Charleston', 'Huntington', 'Parkersburg'],
  WI: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'],
  WY: ['Cheyenne', 'Casper', 'Laramie'],
}

export const NICHES = [
  // Home Services
  { value: 'plumber', label: 'Plumber' },
  { value: 'hvac', label: 'HVAC' },
  { value: 'electrician', label: 'Electrician' },
  { value: 'roofer', label: 'Roofer' },
  { value: 'landscaping', label: 'Landscaping' },
  { value: 'cleaning', label: 'Cleaning Service' },
  { value: 'pest_control', label: 'Pest Control' },
  { value: 'general_contractor', label: 'General Contractor' },
  { value: 'painter', label: 'Painter' },
  { value: 'carpet_cleaning', label: 'Carpet Cleaning' },
  { value: 'flooring', label: 'Flooring' },
  { value: 'windows_doors', label: 'Windows & Doors' },

  // Automotive
  { value: 'auto_repair', label: 'Auto Repair' },
  { value: 'car_wash', label: 'Car Wash' },
  { value: 'tire_shop', label: 'Tire Shop' },
  { value: 'auto_body', label: 'Auto Body' },

  // Health & Wellness
  { value: 'dentist', label: 'Dentist' },
  { value: 'chiropractor', label: 'Chiropractor' },
  { value: 'physical_therapy', label: 'Physical Therapy' },
  { value: 'massage', label: 'Massage Therapy' },
  { value: 'gym', label: 'Gym / Fitness' },
  { value: 'yoga', label: 'Yoga' },

  // Professional Services
  { value: 'accountant', label: 'Accountant / CPA' },
  { value: 'lawyer', label: 'Lawyer / Attorney' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'insurance', label: 'Insurance' },

  // Food & Beverage
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'coffee_shop', label: 'Coffee Shop' },
  { value: 'bar_pub', label: 'Bar / Pub' },
  { value: 'catering', label: 'Catering' },

  // Retail & Shopping
  { value: 'retail', label: 'Retail' },
  { value: 'salon', label: 'Hair Salon' },
  { value: 'barbershop', label: 'Barber Shop' },
  { value: 'spa', label: 'Spa' },

  // Misc
  { value: 'photography', label: 'Photography' },
  { value: 'event_planning', label: 'Event Planning' },
  { value: 'tutoring', label: 'Tutoring' },
  { value: 'dog_grooming', label: 'Dog Grooming' },
]

export const US_STATES = [
  { value: 'AL', label: 'Alabama' }, { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' }, { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' }, { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' }, { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' }, { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' }, { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' }, { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' }, { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' }, { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' }, { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' }, { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' }, { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' }, { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' }, { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' }, { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' }, { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' }, { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' }, { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' }, { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' }, { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' }, { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' }, { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' }, { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' }, { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' }, { value: 'WY', label: 'Wyoming' },
]
